#A Joke teller program
print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black Hole!')
print()
print('Knock Knock!')
input()
print('Who´s there?')
input()
print('interrupting cow.')
input()
print('Interrupting cow wh', end='')
print('-Moo!')
